---

- hosts: all
  become: true
  tasks:

# Ubuntu tasks

  - name: install apache2 and php packages for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

# CentOS tasks

  - name: install httpd and php packages for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

# Use variables instead of 'when'
#
# - name: install apache2 and php with variables
#   package:
#     name:
#       - "{{ apache_package }}"
#       - "{{ php_package }}"
#     state: latest
#     update_cache: yes
