---

# All hosts

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

# Specific hosts
# Web servers

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php packages for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

# Database servers

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb for Ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
    
  - name: install mariadb on CentOS
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

# File servers   

- hosts: file_servers
  become: true
  tasks:

  - name: install samba
    package:
      name: samba
      state: latest

