- name: install mariadb for Ubuntu
  tags: ubuntu,mariadb,db
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
  
- name: install mariadb on CentOS
  tags: centos,mariadb,db
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"
